version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333"]
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    depends_on:
      - db
      - qdrant
